import { Style, ItemType, Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: '简约仿古温润床',
    nameEn: 'Simple Antique Warm Bed',
    nameFr: 'Lit Antique Chaleureux',
    nameEs: 'Cama Antigua Cálida',
    nameJa: 'シンプルなアンティーク調の温かみのあるベッド',
    style: Style.SIMPLE_EURO,
    type: ItemType.BED,
    image: 'https://i.imgs.ovh/2025/12/03/CeoueF.jpeg',
    description: '简约仿古风格床，线条柔和，适配复古风卧室',
    descriptionEn: 'Simple antique style bed with soft lines, perfect for vintage bedrooms.',
    descriptionFr: 'Lit de style antique simple aux lignes douces, parfait pour les chambres vintage.',
    descriptionEs: 'Cama de estilo antiguo simple con líneas suaves, ideal para dormitorios vintage.',
    descriptionJa: '柔らかなラインが特徴のシンプルなアンティーク調ベッド。ヴィンテージ風の寝室に最適です。'
  },
  {
    id: '2',
    name: '经典复刻仿古床',
    nameEn: 'Classic Replica Antique Bed',
    nameFr: 'Lit Antique Réplique Classique',
    nameEs: 'Cama Antigua Réplica Clásica',
    nameJa: 'クラシック復刻アンティークベッド',
    style: Style.SIMPLE_EURO,
    type: ItemType.BED,
    image: 'https://i.imgs.ovh/2025/12/03/Ceowgc.jpeg',
    description: '经典仿古造型床，风格浓郁，质感沉稳',
    descriptionEn: 'Classic antique shaped bed with a rich style and steady texture.',
    descriptionFr: 'Lit de forme antique classique avec un style riche et une texture stable.',
    descriptionEs: 'Cama de forma antigua clásica con un estilo rico y textura estable.',
    descriptionJa: '重厚感のあるクラシックなアンティークベッド。落ち着いた質感が特徴です。'
  },
  {
    id: '3',
    name: '仿古鎏金多功能餐边柜',
    nameEn: 'Antique Gilded Sideboard',
    nameFr: 'Buffet Antique Doré',
    nameEs: 'Aparador Antiguo Dorado',
    nameJa: 'アンティーク調金箔多機能サイドボード',
    style: Style.SIMPLE_EURO,
    type: ItemType.SIDEBOARD,
    image: 'https://i.imgs.ovh/2025/12/03/Ceo1Yp.jpeg',
    description: '仿古框架 + 金色装饰的餐边柜，兼具储物与装饰性',
    descriptionEn: 'Sideboard with antique frame and gold accents, combining storage and decoration.',
    descriptionFr: 'Buffet avec cadre antique et accents dorés, alliant rangement et décoration.',
    descriptionEs: 'Aparador con marco antiguo y detalles dorados, combina almacenamiento y decoración.',
    descriptionJa: 'アンティークなフレームに金色の装飾を施したサイドボード。収納と装飾性を兼ね備えています。'
  },
  {
    id: '4',
    name: '仿古鎏金雕花餐椅',
    nameEn: 'Antique Gilded Carved Chair',
    nameFr: 'Chaise Sculptée Antique Dorée',
    nameEs: 'Silla Tallada Antigua Dorada',
    nameJa: 'アンティーク調金箔彫刻ダイニングチェア',
    style: Style.SIMPLE_EURO,
    type: ItemType.DINING_CHAIR,
    image: 'https://i.imgs.ovh/2025/12/03/Ceo336.jpeg',
    description: '仿古造型餐椅，带金色装饰，适配同系列餐边柜 / 餐桌',
    descriptionEn: 'Antique styled dining chair with gold decoration, matches the same collection.',
    descriptionFr: 'Chaise de salle à manger de style antique avec décoration dorée.',
    descriptionEs: 'Silla de comedor de estilo antiguo con decoración dorada.',
    descriptionJa: '金色の装飾が施されたアンティーク調チェア。同シリーズの家具と調和します。'
  },
  {
    id: '5',
    name: '仿古鎏金精致床前凳',
    nameEn: 'Antique Gilded Bed Bench',
    nameFr: 'Banc de Lit Antique Doré',
    nameEs: 'Banco de Pie de Cama Dorado',
    nameJa: 'アンティーク調金箔ベッドエンドベンチ',
    style: Style.SIMPLE_EURO,
    type: ItemType.STOOL,
    image: 'https://i.imgs.ovh/2025/12/03/CeoiUO.jpeg',
    description: '小巧精致的仿古床前凳，带金色装饰，适配同系列床具',
    descriptionEn: 'Exquisite antique bed bench with gold accents, perfectly matches the bed series.',
    descriptionFr: 'Banc de lit antique exquis avec des accents dorés.',
    descriptionEs: 'Exquisito banco de pie de cama antiguo con detalles dorados.',
    descriptionJa: 'コンパクトで洗練されたアンティーク調ベンチ。金色の装飾が寝室を彩ります。'
  },
  {
    id: '9',
    name: '仿古白金绿撞色大圆几',
    nameEn: 'Antique Tri-color Round Table',
    nameFr: 'Table Basse Ronde Antique',
    nameEs: 'Mesa de Centro Redonda Antigua',
    nameJa: 'アンティーク調配色ラウンドテーブル',
    style: Style.SIMPLE_EURO,
    type: ItemType.COFFEE_TABLE,
    image: 'https://i.imgs.ovh/2025/12/03/Ce4OeY.jpeg',
    description: '白 + 金绿撞色的仿古圆几，色彩层次丰富，适配轻奢复古空间',
    descriptionEn: 'White, gold, and green antique round table with rich layers of color.',
    descriptionFr: 'Table ronde antique blanche, dorée et verte aux couleurs riches.',
    descriptionEs: 'Mesa redonda antigua blanca, dorada y verde con ricas capas de color.',
    descriptionJa: 'ホワイト、ゴールド、グリーンの配色が鮮やかなアンティーク調ラウンドテーブル。'
  },
  {
    id: '11',
    name: '仿古白金绿单人休闲沙发',
    nameEn: 'Antique Single Leisure Sofa',
    nameFr: 'Canapé Simple Antique',
    nameEs: 'Sofá Individual Antiguo',
    nameJa: 'アンティーク調シングルソファ',
    style: Style.SIMPLE_EURO,
    type: ItemType.SOFA,
    image: 'https://i.imgs.ovh/2025/12/03/Ce4ZKb.png',
    description: '单人位仿古沙发，白绿主色调 + 金色线条，造型优雅',
    descriptionEn: 'Single seater antique sofa with white-green tones and gold lines.',
    descriptionFr: 'Canapé antique monoplace aux tons blanc-vert et lignes dorées.',
    descriptionEs: 'Sofá antiguo de una plaza con tonos blanco-verdes y líneas doradas.',
    descriptionJa: 'ホワイトとグリーンを基調とした、優雅なフォルムのシングルソファ。'
  },
  {
    id: '15',
    name: '仿古鎏金三人舒适沙发',
    nameEn: 'Antique Three-Seater Gilded Sofa',
    nameFr: 'Canapé Antique Trois Places Doré',
    nameEs: 'Sofá Antiguo de Tres Plazas Dorado',
    nameJa: 'アンティーク調金箔3人掛けソファ',
    style: Style.SIMPLE_EURO,
    type: ItemType.SOFA,
    image: 'https://i.imgs.ovh/2025/12/03/Ce4Luh.jpeg',
    description: '三人位仿古沙发，主体复古造型 + 金色装饰，坐面宽敞',
    descriptionEn: 'Three-seater antique sofa with a vintage frame and spacious seating.',
    descriptionFr: 'Canapé antique trois places avec un cadre vintage et une assise spacieuse.',
    descriptionEs: 'Sofá antiguo de tres plazas con marco vintage y asiento espacioso.',
    descriptionJa: 'ゆったりとした座面の3人掛けアンティークソファ。豪華な装飾が特徴です。'
  },
  {
    id: '17',
    name: '仿古鎏金实木书桌',
    nameEn: 'Antique Gilded Solid Wood Desk',
    nameFr: 'Bureau Antique en Bois Massif',
    nameEs: 'Escritorio Antiguo de Madera Maciza',
    nameJa: 'アンティーク調金箔無垢材デスク',
    style: Style.SIMPLE_EURO,
    type: ItemType.DESK,
    image: 'https://i.imgs.ovh/2025/12/03/Ce4Ure.jpeg',
    description: '仿古造型书桌，带金色装饰，适配复古风书房',
    descriptionEn: 'Antique style desk with gold accents, ideal for vintage study rooms.',
    descriptionFr: 'Bureau de style antique avec des accents dorés, idéal pour les bureaux vintage.',
    descriptionEs: 'Escritorio de estilo antiguo con detalles dorados, ideal para estudios vintage.',
    descriptionJa: '書斎を格調高く演出する、金色の装飾を施したアンティーク調無垢材デスク。'
  },
  {
    id: '50',
    name: '轻盈优雅床',
    nameEn: 'Light Elegant Bed',
    nameFr: 'Lit Élégant Léger',
    nameEs: 'Cama Ligera y Elegante',
    nameJa: 'エレガントな軽量ベッド',
    style: Style.SIMPLE_EURO,
    type: ItemType.BED,
    image: 'https://i.imgs.ovh/2025/12/03/Ce4iEC.jpeg',
    description: 'C 系列欧式床具，造型轻盈优雅，适配轻奢欧式卧室',
    descriptionEn: 'C Series European bed with a light and elegant design.',
    descriptionFr: 'Lit européen de la série C au design léger et élégant.',
    descriptionEs: 'Cama europea Serie C con un diseño ligero y elegante.',
    descriptionJa: 'Cシリーズの欧風ベッド。軽やかでエレガントなデザインが寝室に溶け込みます。'
  }
];

export const STYLES = Object.values(Style);
export const ITEM_TYPES = Object.values(ItemType);
